on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: deta
          POSTGRES_PASSWORD: deta
          POSTGRES_DATABASE: deta
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.1'
        local_catalogs: $GITHUB_WORKSPACE
    - name: Register local packages
      run: |
        raco pkg install -i --auto --no-setup --skip-installed gillette-test
        raco pkg update --auto --no-setup gillette-lib gillette-doc gillette gillette-test
    - run: raco setup --check-pkg-deps gillette
    - run: raco test -j 4 gillette-lib/ gillette-test/
