on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.7
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: "CS"
        version: "8.6"
        local_catalogs: $GITHUB_WORKSPACE
        dest: '/opt/racketdist'
        sudo: never
    - name: Install pkg and deps
      run: raco pkg install --batch --auto laramie-lib/ laramie-doc/ laramie-test/ laramie/
    - name: Check for unnecessary dependencies
      run: raco setup --check-pkg-deps laramie-lib
    - name: Run package-internal tests
      run: raco test -j 4 laramie-lib/
    - name: Run package-external tests
      run: raco test -j 4 laramie-test/
