on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    matrix:
      racket-version: ["current"]
      racket-variant: ["CS"]
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: ${{ matrix.racket-variant }}
        version: ${{ matrix.racket-version }}
        local_catalogs: $GITHUB_WORKSPACE
        dest: '"${HOME}/racketdist-${{ matrix.racket-version }}-${{ matrix.racket-variant }}"'
    - name: Register local packages
      run: |
        raco pkg install -i --auto --no-setup --skip-installed gillette-test
        raco pkg update --auto --no-setup gillette-lib gillette-doc gillette gillette-test
    - run: raco setup --check-pkg-deps gillette
    - run: raco test -j 4 gillette-lib/ gillette-test/
