on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.5
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: "CS"
        version: "8.1"
        local_catalogs: $GITHUB_WORKSPACE
        dest: '/opt/racketdist'
        sudo: never
    - name: Register local packages
      run: |
        raco pkg install -i --auto --no-setup --skip-installed laramie laramie-test
        raco pkg update --auto --no-setup laramie-lib laramie-doc laramie laramie-test
    - run: raco setup --check-pkg-deps laramie
    - run: raco test -j 4 laramie-lib/ laramie-test/
